# Generated by Django 4.2.7 on 2026-10-02 10:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_project_options_alter_project_cm_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='cost',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cost',
            name='paid_by',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='cost',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='loan_adjusted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='realized_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='buyer_ref',
            field=models.CharField(blank=True, help_text="The buyer's own order / PO number.", max_length=100),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_type',
            field=models.CharField(choices=[('fabric', 'Fabric'), ('accessories', 'Accessories'), ('production', 'Production'), ('washing', 'Washing'), ('printing', 'Printing'), ('embroidery', 'Embroidery'), ('transport', 'Transport'), ('inspection', 'Inspection'), ('lc_charges', 'LC Charges'), ('commission', 'Commission'), ('documentation', 'Documentation'), ('courier', 'Courier'), ('other', 'Other'), ('rent', 'Rent'), ('utilities', 'Utilities (power, gas, water)'), ('salaries', 'Salaries & Wages'), ('office', 'Office Expenses'), ('maintenance', 'Repair & Maintenance'), ('bank_charges', 'Bank Charges'), ('travel', 'Travel & Conveyance'), ('entertainment', 'Entertainment'), ('taxes', 'Taxes & Fees'), ('miscellaneous', 'Miscellaneous'), ('overall_other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cost',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='letterofcredit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('order', 'Order Confirmed'), ('production', 'In Production'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='order', max_length=20),
        ),
        migrations.CreateModel(
            name='LCLoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payment', 'Repayment'), ('lc_adjustment', 'Adjusted from LC')], default='payment', max_length=20)),
                ('repayment_date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default='bank', max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lc_loan_repayments', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='accounts.lcloan')),
            ],
            options={
                'ordering': ['-repayment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('fabric', 'Fabric'), ('accessories', 'Accessories'), ('production', 'Production'), ('washing', 'Washing'), ('printing', 'Printing'), ('embroidery', 'Embroidery'), ('transport', 'Transport'), ('inspection', 'Inspection'), ('lc_charges', 'LC Charges'), ('commission', 'Commission'), ('documentation', 'Documentation'), ('courier', 'Courier'), ('other', 'Other'), ('rent', 'Rent'), ('utilities', 'Utilities (power, gas, water)'), ('salaries', 'Salaries & Wages'), ('office', 'Office Expenses'), ('maintenance', 'Repair & Maintenance'), ('bank_charges', 'Bank Charges'), ('travel', 'Travel & Conveyance'), ('entertainment', 'Entertainment'), ('taxes', 'Taxes & Fees'), ('miscellaneous', 'Miscellaneous'), ('overall_other', 'Other')], max_length=20)),
                ('voucher_date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_by', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default='cash', max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cost_vouchers', to=settings.AUTH_USER_MODEL)),
                ('cost', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher', to='accounts.cost')),
                ('project', models.ForeignKey(blank=True, help_text='Leave blank for an overall (non-order) cost.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='accounts.project')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('direction', models.CharField(choices=[('in', 'Money In'), ('out', 'Money Out')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default='cash', max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('payment', 'Payment'), ('cost', 'Cost'), ('loan', 'LC Loan Taken'), ('loan_repayment', 'LC Loan Repayment'), ('lc_receipt', 'LC Receipt'), ('transfer', 'Cash / Bank Transfer')], default='manual', max_length=20)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbook_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'cash book entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
