# Generated by Django 4.2.7 on 2026-10-02 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_order_numbers_and_loan_repayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='accounts.supplier'),
        ),
        migrations.AddField(
            model_name='costvoucher',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_vouchers', to='accounts.supplier'),
        ),
    ]
