# Generated by Django 4.2.7 on 2026-10-02 11:01

from django.db import migrations, models


def lc_method_to_bank(apps, schema_editor):
    # "Letter of Credit" is no longer a payment method - LC money is recorded on the LC.
    apps.get_model('accounts', 'Payment').objects.filter(payment_method='lc').update(payment_method='bank')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cost_supplier_costvoucher_supplier'),
    ]

    operations = [
        migrations.RunPython(lc_method_to_bank, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
