# Generated by Django 4.2.7 on 2026-10-02 11:33

from django.db import migrations, models


def costs_are_bdt(apps, schema_editor):
    # Costs were always entered in taka; only the label said USD.
    apps.get_model('accounts', 'Cost').objects.exclude(currency='BDT').update(currency='BDT')
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcpayment',
            name='amount_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='lcpayment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='BDT per USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='BDT per USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='realized_bdt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_payments', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='BDT', max_digits=15),
        ),
        migrations.AlterField(
            model_name='cost',
            name='currency',
            field=models.CharField(default='BDT', max_length=3),
        ),
        migrations.AlterField(
            model_name='lcpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='USD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='letterofcredit',
            name='loan_adjusted',
            field=models.DecimalField(decimal_places=2, default=0, help_text='BDT', max_digits=15),
        ),
        migrations.AlterField(
            model_name='letterofcredit',
            name='realized_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='USD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='BDT', max_digits=15),
        ),
        migrations.RunPython(costs_are_bdt, migrations.RunPython.noop),
    ]
