# Generated by Django 4.2.7 on 2026-09-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='issued_to',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
